const WEEKDAY = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY'
}

const WEEKDAY_LIST = Object.values(WEEKDAY)

module.exports = {
  WEEKDAY,
  WEEKDAY_LIST
}
